apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.11.2-4
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.23.0
    command: ["/busybox/sh", "-c", "sleep 999999"]
    volumeMounts:
      - name: docker-credentials-volume
        mountPath: /kaniko/.docker
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
  - name: kubectl
    image: bitnami/kubectl:1.33.4
    command: ["/bin/bash", "-c", "sleep infinity"]
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
  volumes:
    - name: docker-credentials-volume
      projected:
      sources:
      - secret:
          name: docker-credentials
          items:
            - key: .dockerconfigjson
              path: config.json