
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - 9999999
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
  - name: jnlp
    image: jenkins/inbound-agent:4.11.2-4
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
  - name: kubectl
    image: bitnami/kubectl:1.23.0
    command: ["/bin/bash", "-c", "sleep infinity"]
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: docker-credentials
          items:
            - key: .dockerconfigjson
              path: config.json